# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: TSY KNX IPRouter
version: "latest"
slug: tsy-knx-iprouter
boot: auto
description: Browser the TSY KNX IPRouter From Internet
url: "https://shop62960083.taobao.com/?spm=a21xtw.29978518.0.0"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true
ingress_stream: true
map:
  - addons:rw
  - addon_config:rw
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
options:
  message: "欢迎使用TSY KNX IPRouter"
schema:
  message: "str?"
