#!/bin/sh

# 启动 Nginx
echo "Starting Nginx..."
nginx

# 激活虚拟环境
echo "Activating Python virtual environment..."
. /venv/bin/activate

# 启动 Gunicorn
echo "Starting Gunicorn..."
gunicorn -w 4 -b 127.0.0.1:5000 app:app